name: Auto-Update

on:
  workflow_dispatch:
  schedule:
    - cron:  '0 0 * * *'

jobs:
  update:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        include:
          - url: 'https://aka.ms/MinecraftBetaResources'
            branch: beta
            message: 'Beta resource pack update'
          - url: 'https://aka.ms/resourcepacktemplate'
            branch: stable
            message: 'Resource pack update'
    name: ${{ matrix.message }}
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Download the ressource pack
        run: |
          git rm -rf .
          wget -q -O tmp.zip ${{ matrix.url }}
          unzip tmp.zip
          rm tmp.zip
      - name: Push
        uses: EndBug/add-and-commit@v7
        with:
          author_name: Minecraft Bot
          default_author: github_actions
          branch: ${{ matrix.branch }}
          message: ${{ matrix.message }}
